source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'S&B' do
				pod 'AFNetworking'
				pod 'APParallaxHeader'
				pod 'ECSlidingViewController'
				pod 'Fabric'
				pod 'MBProgressHUD'
				pod 'Reachability'
				pod 'SAMTextView'
				pod 'SDWebImage'
				pod 'TBXML'
end
